### ISSUE TITLE
java.lang.IllegalArgumentException: Can't add an asteroid named ''

### ISSUE THREAD

**Issue by samotiwala** [B612-Asteroid-Institute/adam-hack-days#2]
When testing out the current test.py script but with the dates changed, the test run returned FAILED with the error: "java.lang.IllegalArgumentException: Can't add an asteroid named ''".

Don't know how long this error has been in effect, since previous tests used the same start/end + epoch times and the result always brought in the cached run results since the first run was successful.

This was noticed when trying to test out force propagation models without the dates changed, which also returned the cached results (not sure if this is expected or not, but the force model addition was to include Sun only), which did not show any force models. The dates were changed to test out the force model addition when this error appeared. 

The force model option was then removed and all scripts as is on the repo were tested again, but with different dates and the error still persisted. Which means that this error has been there for some time but went unnoticed.

Not sure where the "asteroid" names are being specified or why this error is being received. A description was added and this error was still appearing.

**Comment by HoodedCrow** [comment]
Hmm, empty asteroid strings should be handled (i.e. ignored). Can you point me to what exactly you are trying to run?

**Comment by HoodedCrow** [comment]
I see the problem. It's fixed in the new version but not pushed yet. Split on an empty string gives an empty string, which is not a valid file name. I will push the fixed version later this week (Friday, hopefully). As an ugly hack until then I added 'Juno' to the two default configurations. Your tests should run now (with slightly messed up gravity).

**Comment by samotiwala** [comment]
Great! Looks like the runs are going now :)
